[project]
name = "web-clockpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django>=4.2.24",
    "matplotlib>=3.9.4",
    "seaborn>=0.13.2",
]
