# Generated by Django 4.2.24 on 2025-09-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='text_files/')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_contents', to='upload.textfile')),
            ],
        ),
    ]
